// <auto-generated> from Enums.cs. Each class maps to table lkp<Name>. </auto-generated>
namespace FileBridge.Core.Entities;

public sealed class EndpointTypeLookup : LookupEntity { }
public sealed class TransferDirectionLookup : LookupEntity { }
public sealed class TransferStatusLookup : LookupEntity { }
public sealed class PostActionTypeLookup : LookupEntity { }
public sealed class SemaphoreModeLookup : LookupEntity { }
public sealed class EncryptionOperationLookup : LookupEntity { }
public sealed class CompressionOperationLookup : LookupEntity { }
public sealed class DuplicatePolicyLookup : LookupEntity { }
public sealed class ScheduleTypeLookup : LookupEntity { }
public sealed class NotificationChannelLookup : LookupEntity { }
public sealed class NotificationEventLookup : LookupEntity { }
public sealed class ApprovalStatusLookup : LookupEntity { }
public sealed class RequestTypeLookup : LookupEntity { }
public sealed class RequestStatusLookup : LookupEntity { }
public sealed class QuarantineStatusLookup : LookupEntity { }
public sealed class AppRoleLookup : LookupEntity { }
public sealed class AuditActionLookup : LookupEntity { }
