// <auto-generated/>
using FileBridge.Core.Entities;
using Microsoft.EntityFrameworkCore;

namespace FileBridge.Infrastructure.Data;

internal static class LookupModel
{
    public static void Register(ModelBuilder b)
    {
        b.Entity<EndpointTypeLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<TransferDirectionLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<TransferStatusLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<PostActionTypeLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<SemaphoreModeLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<EncryptionOperationLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<CompressionOperationLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<DuplicatePolicyLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<ScheduleTypeLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<NotificationChannelLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<NotificationEventLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<ApprovalStatusLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<RequestTypeLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<RequestStatusLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<QuarantineStatusLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<AppRoleLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
        b.Entity<AuditActionLookup>(e => { e.HasKey(x => x.Id); e.Property(x => x.Id).ValueGeneratedNever(); });
    }
}
