<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>FileBridge.Infrastructure</RootNamespace></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="PgpCore" />
    <PackageReference Include="MailKit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FileBridge.Core\FileBridge.Core.csproj" />
  </ItemGroup>
  <ItemGroup><InternalsVisibleTo Include="FileBridge.Tests" /></ItemGroup>
</Project>
